# Generated by Django 4.2.7 on 2023-11-12 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_sidebar'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Browse_rate',
            field=models.IntegerField(default=0, verbose_name='流量率'),
        ),
        migrations.AddField(
            model_name='post',
            name='is_hot',
            field=models.BooleanField(default=False, verbose_name='是否热门'),
        ),
    ]
